config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Welcome routes
  get    '/'               => 'welcome#index', as: 'root'
  get    '/about-us'       => 'welcome#about_us'

  # Users index
  get    '/users'          => 'users#index', as: "users"
  # Signup
  get    '/signup'         => 'users#new',   as: "new_user"
  # Users routes
  post   '/users'          => 'users#create'
  get    '/users/:id'      => 'users#show',  as: "user"
  get    '/users/:id/edit' => 'users#edit',  as: "edit_user"
  put    '/users/:id'      => 'users#update'
  patch  '/users/:id'      => 'users#update'
  delete '/users/:id'      => 'users#destroy'
  # Signin
  get    '/signin'          =>  "users#signin"
  post   '/signin'          =>  "users#create_signin"
  # Signout
  get    '/signout'         =>  "users#signout"
  # delete '/signout'         => 'users'

  # Posts routes
  get    '/posts'          => 'posts#index', as: "posts"
  get    '/posts/new'      => 'posts#new',   as: "new_post"
  post   '/posts'          => 'posts#create'
  get    '/posts/:id'      => 'posts#show',  as: "post"
  get    '/posts/:id/edit' => 'posts#edit',  as: "edit_post"
  put    '/posts/:id'      => 'posts#update'
  patch  '/posts/:id'      => 'posts#update'
  delete '/posts/:id'      => 'posts#destroy'

  # Comments routes
  post '/posts/:id/comments' => 'comments#create', as: "comment"
  get '/posts/:id/comments' => 'posts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 2 }
  validates :password, presence: true, length: { in: 6..20 }
  validates :email, presence: true, uniqueness: true
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    p "hi"

    @user = User.find(session[:user_id])
    puts "USER:"
    puts @user.inspect

    @post = Post.find(params[:id])
    puts "POST"
    puts @post.inspect

    @comment = @post.comments.new(comment_params)
    @comment.save
    redirect_to post_path
  end

  private
  def comment_params
   params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @user = User.find(session[:user_id])
  end
  def new
    @post = Post.new
  end
  def create
    @new_post = Post.new(post_params)
    if @new_post.save
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :new)
    end
  end
  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :edit)
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to url_for(:controller => :posts, :action => :index)
  end

  private
  def post_params
   params.require(:post).permit(:title, :content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @new_user = User.new(user_params)
    @new_user.save
    if @new_user.save
      session[:user_id] = @new_user.id
      redirect_to url_for(:controller => :users, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :new)
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if (@user)
      redirect_to url_for(:controller => :users, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :edit)
    end
  end
  def destroy
    User.delete
    redirect_to url_for(:controller => :users, :action => :index)
 end

  def signin
  end

  # check db & create a session
  def create_signin

    @user = User.where( username: params[:username], password: params[:password] ).first

    if @user
      session[:user_id] = @user.id
      redirect_to url_for(:controller => :welcome, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :signin)
    end
  end

  def signout
    session[:user_id] = nil
    redirect_to root_path
  end
  
 private
 def user_params
   params.require(:user).permit(:username, :password, :email)
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if !session[:user_id]
      @user = "stranger"
    else
      @user = User.find(session[:user_id])
    end
  end
  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<br>
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <%= form_for :comment, url: {controller: :comments, action: :create} do |f| %>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
      <%= f.hidden_field :post_id, :value => params[:id] %> <br>
      <%= f.label :content %>
      <%= f.text_area :content %> <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flameo</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="navbar-header">
            <a href="/" style="margin: 0; float: none; text-align:center"><img class="navbar-brand" src="../images/flameo.png"/></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if session[:user_id] %>
                <li>
                    <a href="/users">Users</a>
                </li>
                <li>
                    <a href="/posts">Posts</a>
                </li>
                <% end %>
            </ul>
            <div class="navbar-header pull-right">
                <% if session[:user_id]%>
                <p class="navbar-text">
                    <!-- <a href="/signout" class="navbar-link">Sign out</a> -->
                    <%= link_to 'Sign out',signout_path %>
                </p>
                <% else %>
                <p class="navbar-text">
                    <a href="/signup" class="navbar-link">Sign up</a>
                </p>
                <p class="navbar-text">
                    <a href="/signin" class="navbar-link">Sign in</a>
                </p>
                <% end %>
            </div>
        </div>
    </nav>
    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/posts/_new.html.erb
<br>
<div class="row">
	<div class="col-md-4 col-centered text-center">
		<%= form_for Post.new do |f| %>
		  <%= f.hidden_field :user_id, :value => session[:user_id] %> <br>
		  <%= f.label :title %>
		  <%= f.text_field :title %> <br>
		  <%= f.label :content %>
		  <%= f.text_area :content %> <br>
		  <%= f.submit %>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <%= form_for @post do |f| %>
      <%= f.hidden_field :user_id, :value => session[:user_id] %> <br>
      <%= f.label :title %>
      <%= f.text_field :title %> <br>
      <%= f.label :content %>
      <%= f.text_area :content %> <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <h1>Main posts page</h1>
    <%= @message %>
    <br>
    <% @posts.each do |post| %>
      <%= link_to post.title, comment_path(post.id) %> <br>
    <% end  %>
  </div>
</div>
<%= render 'posts/new' %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-12 title-centered text-center"><h1><%= @post.title %></h1></div>
  <div class="col-md-4 col-centered text-center">
  <a href="/users/<%= @post.user.id %>"><%= @post.user.username %></a><br><br>
		<p class="content-centered"><%= @post.content %></p><br>
		<% if session[:user_id] == @post.user_id %>
			<%= link_to "Edit", edit_post_path(@post) %>
			<%= link_to "Delete", post_path(@post), method: :delete,	data: { confirm: "Do you really want to delete your post?" } %>
		<% end %>
	</div>
</div><br/><br/>
<div class="row">
	<div class="col-md-4 text-center title-centered">
			<% @post.comments.each do |comment| %>
		<div class="text-center user user-comment">
			<a href="/users/<%= comment.user.id %>"><%= comment.user.username %></a>
			<div class="text-center user-content">
				<%= comment.content %>
			</div>
		</div>
	</div>
	<% end %>
</div>
<%= render 'comments/form' %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %> <br>
  <%= f.label :password %>
  <%= f.text_field :password %> <br>
  <%= f.label :email %>
  <%= f.email_field :email %> <br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <h1>Main page</h1>
    <%= @message %>
    <br>
    <% @users.each do |user| %>
      <%= link_to user.username, user_path(user.id) %> <br>
    <% end %>

app/views/users/login_form.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

<%= @message %>


<%= form_tag("/login", method: "post") do %>

  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %><br>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>

  <%= submit_tag("Submit") %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <h1 class="sign">You won't regret it!</h1>
      <br>
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <br>
      <%= f.text_field :username %>
      <br>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password %>
      <br>
      <%= f.label :email %>
      <br>
      <%= f.email_field :email %>
      <br><br>
      <%= submit_tag("Sign up", :class => "btn-danger") %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <br>
    ID: <%= @user.id %><br>
    Username: <%= @user.username %><br>
    E-mail: <%= @user.email %>
    <br>
    <% if session[:user_id] == @user.id %>
    <%= link_to 'Destroy',  { action: :destroy, id: @user.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/users/signin.html.erb
<div class="row">
  <div class="col-md-4 col-centered text-center">
    <h1 class="sign">Flameo awaits!</h1>
      <br>
    <%= form_tag("/signin", method: "post") do %>
    <p class="signin">
      <%= label_tag(:username, "Username") %>
      <br/>
      <%= text_field_tag(:username) %><br>
      <br/>
      <%= label_tag(:password, "Password") %>
      <br/>
      <%= password_field_tag(:password) %>
    </p>
      <br/>
      <%= submit_tag("Sign in", :class => "btn-danger") %>
    <% end %>
  <%= @message %>
  </div>
</div>

app/views/welcome/about_us.html.erb
<%= @message %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12 text-center title centered" style="padding: 100px; padding-top: 50px; padding-bottom: 50px;">
    <% if session[:user_id] != nil %>
      <h1 class="homeheader">Hey, <%= @user.username %></h1>
      <img width="256px" height="256" src="../images/flameo-existing.gif"/>
    <% elsif session[:user_id] == nil %>
    <h1 class="homeheader">Welcome to Flameo, stranger!</h1>
    <img width="256px" height="256" src="../images/flameo-stranger.gif"/>
    <% end %>
  </div>
</div>